import { Task, TeamMember } from './types';

export const initialTasks: Task[] = [
  {
    id: 1,
    phase: 'Fase 1 - Orden estratégico',
    type: 'Reunión',
    title: 'Realizar reunión fundacional Lucas + Gustavo',
    expectedResult: 'Alinear visión, roles y prioridades iniciales',
    responsible: 'Lucas + Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-05-26',
    targetDate: '2026-05-28',
    progress: 0,
    observations: 'Usar agenda de bases de Grow Labs',
  },
  {
    id: 2,
    phase: 'Fase 1 - Orden estratégico',
    type: 'Documento',
    title: 'Definir misión, visión y valores',
    expectedResult: 'Identidad corporativa clara y defendible',
    responsible: 'Lucas + Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-05-27',
    targetDate: '2026-05-30',
    progress: 0,
  },
  {
    id: 3,
    phase: 'Fase 1 - Orden estratégico',
    type: 'Documento',
    title: 'Definir propuesta de valor diferencial',
    expectedResult: 'Frase que resuma por qué elegirnos',
    responsible: 'Lucas + Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-05-28',
    targetDate: '2026-06-01',
    progress: 0,
  },
  {
    id: 4,
    phase: 'Fase 1 - Orden estratégico',
    type: 'Documento',
    title: 'Definir servicios a ofrecer',
    expectedResult: 'Lista clara de servicios con descripción',
    responsible: 'Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-05-29',
    targetDate: '2026-06-03',
    progress: 0,
  },
  {
    id: 5,
    phase: 'Fase 2 - Modelo de negocio',
    type: 'Decisión',
    title: 'Definir ticket mínimo por servicio',
    expectedResult: 'Piso de rentabilidad para cada línea',
    responsible: 'Lucas + Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-06-01',
    targetDate: '2026-06-07',
    progress: 0,
  },
  {
    id: 6,
    phase: 'Fase 2 - Modelo de negocio',
    type: 'Decisión',
    title: 'Definir cliente ideal',
    expectedResult: 'Perfil de cliente objetivo y clientes a evitar',
    responsible: 'Lucas + Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-06-03',
    targetDate: '2026-06-09',
    progress: 0,
  },
  {
    id: 7,
    phase: 'Fase 2 - Modelo de negocio',
    type: 'Documento',
    title: 'Redactar propuesta de valor',
    expectedResult: 'Mensaje comercial claro y defendible',
    responsible: 'Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-06-05',
    targetDate: '2026-06-11',
    progress: 0,
  },
  {
    id: 8,
    phase: 'Fase 2 - Modelo de negocio',
    type: 'Decisión',
    title: 'Definir formas de cobro',
    expectedResult: 'Modelos: diagnóstico, proyecto, mensualidad y mantenimiento',
    responsible: 'Lucas + Gustavo',
    priority: 'Media',
    status: 'Pendiente',
    startDate: '2026-06-07',
    targetDate: '2026-06-14',
    progress: 0,
  },
  {
    id: 9,
    phase: 'Fase 2 - Modelo de negocio',
    type: 'Matriz',
    title: 'Crear matriz de servicios a priorizar/postergar',
    expectedResult: 'Criterio para decidir qué vender ahora',
    responsible: 'Gustavo',
    priority: 'Media',
    status: 'Pendiente',
    startDate: '2026-06-08',
    targetDate: '2026-06-15',
    progress: 0,
  },
  {
    id: 10,
    phase: 'Fase 3 - Sistema comercial',
    type: 'Proceso',
    title: 'Crear protocolo de primer contacto',
    expectedResult: 'Saber qué hacer cuando un cliente consulta',
    responsible: 'Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-06-10',
    targetDate: '2026-06-17',
    progress: 0,
  },
  {
    id: 11,
    phase: 'Fase 3 - Sistema comercial',
    type: 'Plantilla',
    title: 'Diseñar ficha de diagnóstico del cliente',
    expectedResult: 'Capturar datos mínimos antes de presupuestar',
    responsible: 'Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-06-11',
    targetDate: '2026-06-19',
    progress: 0,
  },
  {
    id: 12,
    phase: 'Fase 3 - Sistema comercial',
    type: 'Guion',
    title: 'Armar guion de primera reunión comercial',
    expectedResult: 'Reuniones más ordenadas y orientadas a diagnóstico',
    responsible: 'Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-06-12',
    targetDate: '2026-06-20',
    progress: 0,
  },
  {
    id: 13,
    phase: 'Fase 3 - Sistema comercial',
    type: 'Plantilla',
    title: 'Crear plantilla de propuesta comercial',
    expectedResult: 'Propuestas claras, comparables y profesionales',
    responsible: 'Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-06-13',
    targetDate: '2026-06-23',
    progress: 0,
  },
  {
    id: 14,
    phase: 'Fase 3 - Sistema comercial',
    type: 'Proceso',
    title: 'Definir seguimiento de oportunidades',
    expectedResult: 'Estados comerciales y próximos pasos definidos',
    responsible: 'Gustavo',
    priority: 'Media',
    status: 'Pendiente',
    startDate: '2026-06-15',
    targetDate: '2026-06-25',
    progress: 0,
  },
  {
    id: 15,
    phase: 'Fase 4 - Sistema operativo',
    type: 'Proceso',
    title: 'Crear proceso de onboarding del cliente',
    expectedResult: 'Inicio de proyecto ordenado y sin improvisación',
    responsible: 'Lucas + Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-06-17',
    targetDate: '2026-06-27',
    progress: 0,
  },
  {
    id: 16,
    phase: 'Fase 4 - Sistema operativo',
    type: 'Checklist',
    title: 'Armar checklist de información inicial',
    expectedResult: 'Datos, accesos y documentos requeridos por proyecto',
    responsible: 'Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-06-19',
    targetDate: '2026-06-30',
    progress: 0,
  },
  {
    id: 17,
    phase: 'Fase 4 - Sistema operativo',
    type: 'Tablero',
    title: 'Definir tablero de seguimiento de proyectos',
    expectedResult: 'Control de avances por cliente y entregable',
    responsible: 'Lucas + Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-06-21',
    targetDate: '2026-07-03',
    progress: 0,
  },
  {
    id: 18,
    phase: 'Fase 4 - Sistema operativo',
    type: 'Plantilla',
    title: 'Crear modelo de informe de avance',
    expectedResult: 'Comunicación profesional con clientes',
    responsible: 'Gustavo',
    priority: 'Media',
    status: 'Pendiente',
    startDate: '2026-06-23',
    targetDate: '2026-07-07',
    progress: 0,
  },
  {
    id: 19,
    phase: 'Fase 4 - Sistema operativo',
    type: 'Política',
    title: 'Definir política de cambios de alcance',
    expectedResult: 'Evitar pedidos fuera de alcance sin control',
    responsible: 'Lucas + Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-06-25',
    targetDate: '2026-07-10',
    progress: 0,
  },
  {
    id: 20,
    phase: 'Fase 5 - Gestión interna',
    type: 'Documento',
    title: 'Definir roles Lucas / Gustavo',
    expectedResult: 'Responsabilidades y decisiones claras',
    responsible: 'Lucas + Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-05-29',
    targetDate: '2026-06-03',
    progress: 0,
  },
  {
    id: 21,
    phase: 'Fase 5 - Gestión interna',
    type: 'Rutina',
    title: 'Instalar reunión semanal de gestión',
    expectedResult: 'Seguimiento constante de prioridades',
    responsible: 'Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-05-27',
    targetDate: '2026-05-31',
    progress: 0,
    observations: 'Frecuencia sugerida: 1 vez por semana',
  },
  {
    id: 22,
    phase: 'Fase 5 - Gestión interna',
    type: 'Registro',
    title: 'Crear registro de decisiones',
    expectedResult: 'Que las decisiones no queden en WhatsApp o memoria',
    responsible: 'Gustavo',
    priority: 'Media',
    status: 'Pendiente',
    startDate: '2026-05-31',
    targetDate: '2026-06-05',
    progress: 0,
  },
  {
    id: 23,
    phase: 'Fase 5 - Gestión interna',
    type: 'Indicadores',
    title: 'Definir indicadores mínimos de gestión',
    expectedResult: 'Medir avance, ventas, proyectos y calidad',
    responsible: 'Gustavo',
    priority: 'Media',
    status: 'Pendiente',
    startDate: '2026-06-05',
    targetDate: '2026-06-13',
    progress: 0,
  },
  {
    id: 24,
    phase: 'Fase 6 - Plan 30/60/90',
    type: 'Plan',
    title: 'Armar plan de acción a 30 días',
    expectedResult: 'Acciones urgentes y responsables claros',
    responsible: 'Gustavo',
    priority: 'Alta',
    status: 'Pendiente',
    startDate: '2026-05-31',
    targetDate: '2026-06-07',
    progress: 0,
  },
  {
    id: 25,
    phase: 'Fase 6 - Plan 30/60/90',
    type: 'Plan',
    title: 'Armar plan de acción a 60 días',
    expectedResult: 'Consolidar modelo comercial y operativo',
    responsible: 'Gustavo',
    priority: 'Media',
    status: 'Pendiente',
    startDate: '2026-06-10',
    targetDate: '2026-06-25',
    progress: 0,
  },
  {
    id: 26,
    phase: 'Fase 6 - Plan 30/60/90',
    type: 'Plan',
    title: 'Armar plan de acción a 90 días',
    expectedResult: 'Sistema inicial de empresa funcionando',
    responsible: 'Lucas + Gustavo',
    priority: 'Media',
    status: 'Pendiente',
    startDate: '2026-06-25',
    targetDate: '2026-07-25',
    progress: 0,
  },
];

export const initialTeamMembers: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Lucas',
    role: 'Director',
    email: 'lucas@growlabs.com',
    joinDate: '2025-01-01',
    active: true,
    skills: ['Desarrollo', 'Arquitectura', 'AI', 'DevOps'],
    currentProjects: [],
  },
  {
    id: 'tm-2',
    name: 'Gustavo',
    role: 'Comercial',
    email: 'gustavo@growlabs.com',
    joinDate: '2026-05-01',
    active: true,
    skills: ['Consultoría', 'Ventas', 'Estrategia', 'Gestión'],
    currentProjects: [],
  },
];
